languageCode = "en-gb"
weight = 1

title = "Blog de Nathan"

[languages.en.params]
# TODO REVIEW WHICH GOES WHERE
color = 'blue'
description = "Gaming, Software Development, Data Science, Fitness"
rtl = false

[author]
# TODO Review -> About page?
name = "Nathan DECOOL"
image = "img/portrait_lowres.jpg"
headline = "Gaming, Software Development, Data Science, Fitness"
# TODO Review (end of pages)
bio = "Gaming, Software Development, Data Science, Fitness"
links = [
    #     { email = "mailto:hello@your_domain.com" },
    #     { link = "https://link-to-some-website.com/" },
    #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #     { apple = "https://www.apple.com" },
    #     { blogger = "https://username.blogspot.com/" },
    #     { codepen = "https://codepen.io/username" },
    #     { dev = "https://dev.to/username" },
    #     { discord = "https://discord.gg/invitecode" },
    #     { dribbble = "https://dribbble.com/username" },
    #     { facebook = "https://facebook.com/username" },
    #     { flickr = "https://www.flickr.com/photos/username/" },
    #     { foursquare = "https://foursquare.com/username" },
    #     { github = "https://github.com/mrtolkien/" },
    #     { gitlab = "https://gitlab.com/username" },
    #     { google = "https://www.google.com/" },
    #     { hashnode = "https://username.hashnode.dev" },
    #     { instagram = "https://instagram.com/username" },
    #     { keybase = "https://keybase.io/username" },
    #     { kickstarter = "https://www.kickstarter.com/profile/username" },
    #     { lastfm = "https://lastfm.com/user/username" },
    #     { linkedin = "https://linkedin.com/in/username" },
    #     { bluesky = "https://bsky.app/profile/tolki.dev" },
    #     { mastodon = "https://fosstodon.org/@tolki" },
    #     { medium = "https://medium.com/username" },
    #     { microsoft = "https://www.microsoft.com/" },
    #     { orcid = "https://orcid.org/userid" },
    #     { patreon = "https://www.patreon.com/username" },
    #     { pinterest = "https://pinterest.com/username" },
    #     { reddit = "https://reddit.com/user/username" },
    #     { researchgate = "https://www.researchgate.net/profile/username" },
    #     { slack = "https://workspace.url/team/userid" },
    #     { snapchat = "https://snapchat.com/add/username" },
    #     { soundcloud = "https://soundcloud.com/username" },
    #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #     { steam = "https://steamcommunity.com/profiles/userid" },
    #     { telegram = "https://t.me/username" },
    #     { tiktok = "https://tiktok.com/@username" },
    #     { tumblr = "https://username.tumblr.com" },
    #     { twitter = "https://twitter.com/tolkicasts" },
    #     { twitch = "https://twitch.tv/tolkicasts" },
    #     { whatsapp = "https://wa.me/phone-number" },
    #     { youtube = "https://www.youtube.com/channel/UC54dcAoEXY2ws6bMjBz8aYA" },
    #     { ko-fi = "https://ko-fi.com/username" },
]
